In [1]:
import numpy as np
from scipy.signal import convolve2d

# Input image (5x5 example)
image = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2],
    [7, 8, 9, 0, 3],
    [1, 3, 2, 1, 0],
    [0, 1, 2, 3, 4]
])

# 3x3 Kernel
kernel = np.array([
    [0, 0, 0],
    [0, 9, 0],
    [0, 0, 0]
])

# Convolution (without padding, stride 1)
output = convolve2d(image, kernel, mode='valid')  # 'valid' = no padding
print(output)


[[45 54  9]
 [72 81  0]
 [27 18  9]]
